### ISSUE TITLE
i18n support

### ISSUE THREAD

**Issue by Raton-Laveur** [stregac/trainers_image_library#13]
Greetings, 

I'd gladly translate bodyshop.js and wardrobe.js to another language, but it seems there's no support for internationalization or location for foreign language strings. Or should I fork the project towards another language? 

Some best practices for adding support can be found here : https://www.w3.org/TR/xml-i18n-bp/#DesignTime 

Thanks!

**Comment by anxtdghiov** [comment]
Not the original author, but... 
I can add <text xml:lang="en"> around the body, is that enough? If not, can you maybe submit a patch or suggest how to fix it? You probably know more about it than I do. You're also free to fork it, of course. I'd welcome anyone who wants to participate, but this best practices text is too long for a best practices, really.

Currently most of the text displayed is in the wardrobe. I'm wondering if this will remain if the consensus is that the larger images as thumbs is the way to go and speak for themselves. In general I feel this is a very early development stage so I'm not sure if it's worth the effort to start with translating as the layout may change..

I know a few languages myself btw, English, German, French, Latin, Dutch, bash, javascript, C, C++, R, perl, python, sed and awk.
