### ISSUE TITLE
Firefox blocks connection to yahooapis.com when accessing site via HTTPS

### ISSUE THREAD

**Issue by AlsaAsksMiley** [stregac/trainers_image_library#9]
When visiting https://stregac.github.io/trainers_image_library/ Firefox blocks [mixed content](https://developer.mozilla.org/docs/Security/MixedContent) from `yui.yahooapis.com` breaking entire webpage, though it's still possible to configure outfit.    
Is it possible to make `pure-min.css` and `grids-responsive-min.css` be loaded over secure connection?    
![Screenshot attached](https://cloud.githubusercontent.com/assets/11726084/12422087/3c1a5bfe-bed6-11e5-8372-6239df670c1f.png)

**Comment by stregac** [comment]
Thank you for reporting this, @AlsaAsksMiley. This issue has been fixed.
